version: '3.7'
services:
  master:
    image: locustio/locust
    ports:
      - "8089:8089"
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/locustfile-issueV1.py --master -H http://host.docker.internal:8080
    # TEST PYTHON File Path Setting + Testing Host URL - 현재는 로컬로 진행 (내부 8080 port- coupon-api)
  worker:
    image: locustio/locust
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/locustfile-issueV1.py --worker --master-host master
